### ISSUE TITLE
Use a dataclass for `parse_filename`

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/noaa-mrms-qpe#11]
Rather than pure dictionaries, [dataclasses](https://docs.python.org/3/library/dataclasses.html) are a helpful way to collect the expected fields from, e.g., https://github.com/stactools-packages/noaa-mrms-qpe/blob/34d9ad450094dfafb827a7823d9cb2ad88396825/src/stactools/noaa_mrms_qpe/stac.py#L290-L308.

**Comment by m-mohr** [comment]
Oh, yes, that is certainly nicer! Thanks.
