### ISSUE TITLE
Review Notes

### ISSUE THREAD

**Issue by pjhartzell** [stactools-packages/noaa-mrms-qpe#13]
1. I believe hyphens, rather than underscores, are typically used for the command names. Line 17 in `commands.py`, `noaa_mrms_qpe` to `noaa-mrms-qpe`.
2. Line 82 in `stac.py`: recommend changing `no Multi-Sensor` ... to `not Multi-Sensor ...`
3. Consider excluding the self link in `examples/collection.json`.
4. I've not see "cloud-optimized" used as an asset role before. It is already specified in `type`, so curious as to the intent for using it in `roles`.
5. For the `aoi` argument in `create_item`: It looks possible to create an item, for example, that uses data from Guam but has an id with the `CONUS` prefix because no value was passed for `aoi` (defaults to `CONUS`). Should that option be required and be from a fixed choice? Or eliminated (and let the item id simply match the filename)?

**Comment by m-mohr** [comment]
Thank you for the review.

> 1. I believe hyphens, rather than underscores, are typically used for the command names.

Fine for me. Fixed.

>     2. Line 82 in `stac.py`: recommend changing `no Multi-Sensor` ... to `not Multi-Sensor ...`

Fixed.

>     3. Consider excluding the self link in `examples/collection.json`.

Why? It helps with visualization in e.g. STAC Browser...

>     4. I've not see "cloud-optimized" used as an asset role before. It is already specified in `type`, so curious as to the intent for using it in `roles`.

That is probably new, indeed. I just tried to give them distinct roles so that you can distinguish the assets better.

>     5. For the `aoi` argument in `create_item`: It looks possible to create an item, for example, that uses data from Guam but has an id with the `CONUS` prefix because no value was passed for `aoi` (defaults to `CONUS`). Should that option be required and be from a fixed choice? Or eliminated (and let the item id simply match the filename)?

I can't read the aoi from the filename so it needs to be specified, but I removed the default value and check against an enum now. That doesn't prevent that a user from specifying non-fitting AOI for a file though.

**Comment by pjhartzell** [comment]
>Why? It helps with visualization in e.g. STAC Browser...

Ah. Makes sense. I guess we usually generate the examples on our local machines and do not want to see a local path for the self link. That's not the case here.

>That doesn't prevent that a user from specifying non-fitting AOI for a file though. To prevent that I'd likely need to do some whacky bbox checks. I hope users know what they do...

Yeah, the user has to take some responsibility. But your update prevents the easier mistake, and I think that's sufficient.
