### ISSUE TITLE
Add an extra field for the region

### ISSUE THREAD

**Issue by pjhartzell** [stactools-packages/noaa-mrms-qpe#18]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to query/filter on one of the regions (CONUS, ALASKA, HAWAII, CARIB, or GUAM). 

**Describe the solution you'd like**
Add an extra field, something like `noaa_mrms_qpe:region`

**Describe alternatives you've considered**
You can just specify a bbox to limit the geographic region of interest, but the ability to filter on a property is arguably more convenient.

**Comment by m-mohr** [comment]
No problem, will do...

**Comment by m-mohr** [comment]
Implemented in commit https://github.com/stactools-packages/noaa-mrms-qpe/commit/087a7a51b49b092fe9001f1c3c82e7e710beb7de

**Comment by m-mohr** [comment]
v0.2.0 is available on PyPi :-) Let me know if you need anything else.

**Comment by pjhartzell** [comment]
Looks good - thanks!
