### ISSUE TITLE
Custom extension schema is "pinned" to main branch

### ISSUE THREAD

**Issue by pjhartzell** [stactools-packages/noaa-mrms-qpe#20]
The schema points to the `main` branch:
```
 "properties": {
        "stac_extensions": {
          "type": "array",
          "contains": {
            "const": "https://raw.githubusercontent.com/stactools-packages/noaa-mrms-qpe/main/extension/schema.json"
          }
        }
      }
```

I think it needs to point to the current release tag. Otherwise, we end up with a mismatch if a user is pinned to an old version of the the package but the schema has been updated (and still references the version in the `main` branch).

**Comment by m-mohr** [comment]
Yeah, I did not expect changes. 
Changing to specific version numbers might be a bit difficult because in dev the tests may not work as expected if changes occur. Is there a way to set to main if run through pytest?

**Comment by pjhartzell** [comment]
The cleanest solution does seem to be to move it to its own repository.

**Comment by m-mohr** [comment]
Migrated to https://github.com/stac-extensions/noaa-mrms-qpe
See also ac705bc5
