### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by m-mohr** [stactools-packages/noaa-mrms-qpe#4]
Tests are succeeding, but they are not checking anything useful. This needs to be improved.

**Comment by m-mohr** [comment]
@gadomski How extensive should tests be?

**Comment by gadomski** [comment]
It's a good question -- I've gone back and forth between testing every single attribute of the STAC item, to only explicitly checking the tricky ones. I'd say a unit tests that checks the essential attributes of the item (especially those that require any sort of calculation), and the values in any extensions, would be useful. Something like https://github.com/stactools-packages/noaa-c-cap/blob/main/tests/test_stac.py.

**Comment by m-mohr** [comment]
Tests have been added.
