### ISSUE TITLE
GSD Use

### ISSUE THREAD

**Issue by pjhartzell** [stactools-packages/noaa-mrms-qpe#5]
Should GSD should be omitted from the Items and Collection? Per the [STAC spec](https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#gsd), GSD is “...spatial resolution at the sensor, rather than the pixel size…”. QPE is generated from data from multiple sensors - not sure if any of them actually have an at sensor pixel field of view of 1000m.

The nominal 1000m pixel size is captured in the `raster:bands` `spatial_resolution` property.

**Comment by m-mohr** [comment]
I added gsd because for the grib cases we don't use raster:bands but the file extension instead (due to multiple no-data values). But then there's no way to specify the spatial resolution... Thoughts?

**Comment by pjhartzell** [comment]
Hmm. Yeah. I don't have a good answer for that. I think a lot of people interpret GSD to mean ground pixel size, so it makes sense to use it as such. But it is also not supposed to mean that. And other than a custom field, I guess there isn't a standard way to express ground pixel size outside of `raster:bands`.  😐

**Comment by m-mohr** [comment]
I could maybe provide both raster:bands and the file extension for GRIB. Leave out nodata from raster:bands and provide it in file:nodata instead. Although I'm not 100% sure whether GRIB actually has the concept of "bands"?

**Comment by m-mohr** [comment]
I'm now generating both file and raster entries for GRIB files.
