### ISSUE TITLE
Raster Extension version and string `nodata` values

### ISSUE THREAD

**Issue by pjhartzell** [stactools-packages/noaa-mrms-qpe#6]
The raster extension in pystac has not been updated to v1.1.0 yet, so it is inserting the v1.0.0 raster extension schema link into the extensions list. The Items and/or Collection will not validate because v1.0.0 does not support the use of "nan" as the `nodata` value.

**Comment by m-mohr** [comment]
"nan" is a placeholder for now as we are not sure yet how to convert no-data from the GRIB file. So may be -1 in the end, but I can also update the raster extension if we use nan. Thanks for the comment.

**Comment by m-mohr** [comment]
nodata value is now -1, so we can still use the old version of the raster extension.
