### ISSUE TITLE
Remove stactools as a provider

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/noaa-mrms-qpe#8]
I like the idea of tracking the software processing lineage, but `Provider` doesn't quite seem to match. From [the spec](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object):

> A provider is any of the organizations that captures or processes the content of the Collection and therefore influences the data offered by this Collection. 

I wouldn't say that the `stactools` organization does any work for these data. I'd probably just make NOAA all four (`producer`, `processor`, `host`, and `licensor`).

**Comment by m-mohr** [comment]
Yeah, it doesn't quite match. Ideally, you'd give an option so that the organization running stactools would add itself to the list. But leaving it in the responsibility of the provider to add themselves and removed stactools from the list.

I'm not sure about adding host and processor though. processor should be included in producer and two hosts in a list (expecting someone else than NOAA to use this package) is also weird.

**Comment by m-mohr** [comment]
> For host, if someone else copies the data then starts hosting it, then they should remove host from NOAA. For now, NOAA is hosting the data, yes?

That is true, but the package can't actually be used to refer to the NOAA files right now so I assume the case where someone creates metadata for the NOAA hosted files seems unlikely. As such everyone needs to remove the host value, which seems like an annoying default.

> We've been including processor for completeness -- e.g. NOAA runs both the radar sensors that are producing the source data, and the processing chain that's producing this derivative product? But I'll admit I don't have a great grasp of the intent behind those provider roles.

Well, I've invented/added them to STAC back in the days. And NOAA produces the original data (i.e. the QPE data). stactools then processes them to a derivate product of QPE. Basically, processor should usually never be present in the first entry of providers (which is a chronological list). That was at least my initial thinking. ;-)

**Comment by gadomski** [comment]
> That is true, but the package can't actually be used to refer to the NOAA files right now so I assume the case where someone creates metadata for the NOAA hosted files seems unlikely. As such everyone needs to remove the host value, which seems like an annoying default.

Ok, that's fair. I'm now 👍🏽 to leaving host off.

> Basically, processor should usually never be present in the first entry of providers (which is a chronological list).

Good to know, this is helpful. Yeah, let's stick with that, since you wrote it and all :-).
