### ISSUE TITLE
Providers can be constants

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/noaa-mrms-qpe#9]
Since we already have a [constants file](https://github.com/stactools-packages/noaa-mrms-qpe/blob/main/src/stactools/noaa_mrms_qpe/constants.py), the providers at https://github.com/stactools-packages/noaa-mrms-qpe/blob/34d9ad450094dfafb827a7823d9cb2ad88396825/src/stactools/noaa_mrms_qpe/stac.py#L45-L57 can live in `constants` as well. Python's less persnickety about constant objects than other languages and we've used this pattern (constant providers) in other packages.

**Comment by m-mohr** [comment]
Moved to constants.
